local parser = require('logseq.parser')

describe('parser.links_in_line (M0 smoke)', function()
  it('finds a single [[wikilink]]', function()
    local links = parser.links_in_line('- Hello [[World]]')
    assert.are.equal(1, #links)
    assert.are.equal('World', links[1].text)
    assert.are.equal('wikilink', links[1].kind)
  end)
end)

describe('parser.links_in_line (M2)', function()
  it('reports multiple links ordered with columns and kinds', function()
    local links = parser.links_in_line('- see [[B]] and #tag here')
    assert.are.equal(2, #links)
    assert.are.same({ text = 'B', col_start = 7, col_end = 11, kind = 'wikilink' }, links[1])
    assert.are.same({ text = 'tag', col_start = 17, col_end = 20, kind = 'hashtag' }, links[2])
  end)

  it('parses #[[hash-wikilink]] without double-reporting the inner [[..]]', function()
    local links = parser.links_in_line('- #[[a b]] ok')
    assert.are.equal(1, #links)
    assert.are.same({ text = 'a b', col_start = 3, col_end = 10, kind = 'hash-wikilink' }, links[1])
  end)

  it('does not report a #tag inside a [[wikilink]]', function()
    local links = parser.links_in_line('- [[a #b]]')
    assert.are.equal(1, #links)
    assert.are.equal('wikilink', links[1].kind)
    assert.are.equal('a #b', links[1].text)
  end)

  it('keeps [[a/b]] text verbatim (/ resolution is M4)', function()
    local links = parser.links_in_line('[[a/b]]')
    assert.are.equal(1, #links)
    assert.are.equal('a/b', links[1].text)
  end)

  it('stops a #tag before punctuation', function()
    local links = parser.links_in_line('see #logseq, ok')
    assert.are.equal(1, #links)
    assert.are.same({ text = 'logseq', col_start = 5, col_end = 11, kind = 'hashtag' }, links[1])
  end)

  it('skips empties and tolerates non-string input', function()
    assert.are.same({}, parser.links_in_line('- [[]] and # done'))
    assert.are.same({}, parser.links_in_line(nil))
    assert.are.same({}, parser.links_in_line('- nothing here'))
  end)
end)

describe('parser.link_under_cursor (M2)', function()
  it('returns the link containing the 1-based col', function()
    local link = parser.link_under_cursor('- [[B]]', 5)
    assert.are.equal('B', link.text)
    assert.are.equal('wikilink', link.kind)
  end)

  it('counts bracket edges as on the link, outside as off', function()
    assert.is_not_nil(parser.link_under_cursor('- [[B]]', 3))
    assert.is_not_nil(parser.link_under_cursor('- [[B]]', 7))
    assert.is_nil(parser.link_under_cursor('- [[B]]', 2))
    assert.is_nil(parser.link_under_cursor('- [[B]]', 8))
  end)

  it('picks the right link when several share a line', function()
    assert.are.equal('A', parser.link_under_cursor('[[A]] [[B]]', 3).text)
    assert.are.equal('B', parser.link_under_cursor('[[A]] [[B]]', 9).text)
    assert.is_nil(parser.link_under_cursor('[[A]] [[B]]', 6))
  end)

  it('is nil-safe', function()
    assert.is_nil(parser.link_under_cursor(nil, 1))
    assert.is_nil(parser.link_under_cursor('- [[A]]', nil))
    assert.is_nil(parser.link_under_cursor('- plain', 3))
  end)
end)
